version: '3.8'

services:

    elastic-1:
        image: elasticsearch:${ELK_VERSION:-8.17.0}
        hostname: elastic-1
        container_name: elastic-1
        environment:
            - node.name=elastic-1
            - cluster.name=es-nebula-cluster
            - discovery.seed_hosts=elastic-2,elastic-3
            - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        volumes:
            - "./volumes/es_data/elastic-1:/usr/share/elasticsearch/data"
        ports:
            - "9200:9200"
        networks:
            - ${GLOBAL_NETWORK:-elastic}

    elastic-2:
        image: elasticsearch:${ELK_VERSION:-8.17.0}
        container_name: elastic-2
        environment:
            - node.name=elastic-2
            - cluster.name=es-nebula-cluster
            - discovery.seed_hosts=elastic-1,elastic-3
            - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        volumes:
            - "./volumes/es_data/elastic-2:/usr/share/elasticsearch/data"
        networks:
            - ${GLOBAL_NETWORK:-elastic}

    elastic-3:
        image: elasticsearch:${ELK_VERSION:-8.17.0}
        container_name: elastic-3
        environment:
            - node.name=elastic-3
            - cluster.name=es-nebula-cluster
            - discovery.seed_hosts=elastic-1,elastic-2
            - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        volumes:
            - "./volumes/es_data/elastic-3:/usr/share/elasticsearch/data"
        networks:
            - ${GLOBAL_NETWORK:-elastic}