version: '3.8'

services:

    twitter-stream-simulator:
        image: anatolydudko/twitter-stream-simulator:${APP_VERSION:-demo}
        hostname: twitter-stream-simulator
        container_name: twitter-stream-simulator
        ports:
            - "8281:8281"
        environment:
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
        networks:
            - ${GLOBAL_NETWORK:-service}

    twitter-kafka-to-elastic-service:
        image: anatolydudko/twitter-kafka-to-elastic-service:${APP_VERSION:-demo}
        hostname: twitter-kafka-to-elastic-service
        container_name: twitter-kafka-to-elastic-service
        ports:
            - "8381:8381"
        depends_on:
            - twitter-stream-simulator
        environment:
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
            ELASTIC-CONFIG_CONNECTION-URL: elasticsearch:9200
        networks:
            - ${GLOBAL_NETWORK:-service}
