version: '3.8'

services:

    wikimedia-stream-scraper:
        image: anatolydudko/wikimedia-stream-scraper:${APP_VERSION:-demo}
        hostname: wikimedia-stream-scrape
        container_name: wikimedia-stream-scrape
        ports:
            - "8282:8282"
        environment:
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
        networks:
            - ${GLOBAL_NETWORK:-service}

    wikimedia-kafka-to-elastic-service:
        image: anatolydudko/wikimedia-kafka-to-elastic-service:${APP_VERSION:-demo}
        hostname: wikimedia-kafka-to-elastic-service
        container_name: wikimedia-kafka-to-elastic-service
        ports:
            - "8382:8382"
        depends_on:
            - wikimedia-stream-scraper
        environment:
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
            ELASTIC-CONFIG_CONNECTION-URL: elasticsearch:9200
        networks:
            - ${GLOBAL_NETWORK:-service}
