version: '3.8'

services:

    init-kafka:
        image: confluentinc/cp-kafka:${KAFKA_VERSION}
        container_name: init-kafka
        entrypoint: [ '/bin/sh', '-c' ]
        command: |
            "
            # block until kafka is reachable
            kafka-topics --bootstrap-server kafka-broker-1:9092 --list
            
            echo -e 'Deleting kafka topics'
            kafka-topics --bootstrap-server kafka-broker-1:9092 --topic simulator-stream --delete --if-exists
            
            echo -e 'Creating kafka topics'
            kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic simulator-stream --replication-factor 3 --partitions 3
            
            echo -e 'Successfully created the following topics:'
            kafka-topics --bootstrap-server kafka-broker-1:9092 --list
            "
        networks:
            - ${GLOBAL_NETWORK:-kafka}
